### ISSUE TITLE
Screen Raspberry 7 inch PI2

### ISSUE THREAD

**Issue by jeje444** [bigtreetech/CB2#13]
The 7 inch raspberry screen does not work on a PI2, modification of the file 

armabianEnv.txt 
      overlays=dsi

Do not work the screen remains black

Power supply of the screen by an external raspberry 5v power supply

Does somebody have an idea ?

**Comment by igl-x2** [comment]
I have the same problem.
The screen is working! When you tap it you can see the Klipper commands on the web interface.

Problem is the screen is a 0 brightness setting!

**Comment by igl-x2** [comment]
please open a ticket with BTT. I also have one. Its ticket #7107

**Comment by zhangyumingsh** [comment]
> I have the same problem. The screen is working! When you tap it you can see the Klipper commands on the web interface.
> 
> Problem is the screen is a 0 brightness setting!

The newly released image has been resolved
