### ISSUE TITLE
Raspicam v1.3 + crownest

### ISSUE THREAD

**Issue by mojamuto** [bigtreetech/CB2#19]
Good afternoon, I am trying to connect a raspicam v1.3 ov5647, I have followed the instructions in the PDF but I get this error:
![fallo crownest](https://github.com/bigtreetech/CB2/assets/36079583/c704ec9a-f08b-45e2-9a99-cd996fe05f9e)
Searching on the internet, everything refers to libcamera-hello, but it is not in the Armbian image.

**Comment by igl-x2** [comment]
Your config says dev/video9.
Try video0

**Comment by Aergernis** [comment]
Hi,
having the same problem. Tested the camera with a Pi and it's working. 3,3V is present when connected to CB2 with M8P V2.

```
[06/16/24 20:53:36] crowsnest: crowsnest - A webcam Service for multiple Cams and Stream Services.
[06/16/24 20:53:36] crowsnest: Version: v4.1.9-1-gd75a3ae
[06/16/24 20:53:36] crowsnest: Prepare Startup ...
[06/16/24 20:53:36] crowsnest: INFO: Host information:
[06/16/24 20:53:36] crowsnest: Host Info: Distribution: BTT-CB2_1.0.4_Armbian 23.05.0-trunk Bullseye
[06/16/24 20:53:36] crowsnest: Host Info: Kernel: Linux 4.19.232-bigtree-cb2 aarch64
[06/16/24 20:53:36] crowsnest: Host Info: Available CPU Cores: 4
[06/16/24 20:53:36] crowsnest: Host Info: Available Memory: 2029676 kB
[06/16/24 20:53:36] crowsnest: Host Info: Diskspace (avail. / total): 24G / 29G
[06/16/24 20:53:36] crowsnest: INFO: Checking Dependencies
[06/16/24 20:53:36] crowsnest: Dependency: 'crudini' found in /usr/bin/crudini.
[06/16/24 20:53:36] crowsnest: Dependency: 'find' found in /usr/bin/find.
[06/16/24 20:53:36] crowsnest: Dependency: 'xargs' found in /usr/bin/xargs.
[06/16/24 20:53:36] crowsnest: Dependency: 'ustreamer' found in bin/ustreamer/src/ustreamer.bin.
[06/16/24 20:53:36] crowsnest: Version Control: ustreamer is up to date. (v6.10)
[06/16/24 20:53:36] crowsnest: INFO: Print Configfile: '/home/philipp/printer_data/config/crowsnest.conf'
[06/16/24 20:53:36] crowsnest:		[crowsnest]
[06/16/24 20:53:36] crowsnest:		log_path: /home/philipp/printer_data/logs/crowsnest.log
[06/16/24 20:53:36] crowsnest:		log_level: verbose
[06/16/24 20:53:36] crowsnest:		delete_log: false
[06/16/24 20:53:36] crowsnest:		no_proxy: false
[06/16/24 20:53:36] crowsnest:		
[06/16/24 20:53:36] crowsnest:		[cam 1]
[06/16/24 20:53:36] crowsnest:		mode: ustreamer
[06/16/24 20:53:36] crowsnest:		
[06/16/24 20:53:36] crowsnest:		enable_rtsp: false
[06/16/24 20:53:36] crowsnest:		rtsp_port: 8554
[06/16/24 20:53:36] crowsnest:		port: 8080
[06/16/24 20:53:36] crowsnest:		device: /dev/video0
[06/16/24 20:53:36] crowsnest:		resolution: 1920x1080
[06/16/24 20:53:36] crowsnest:		max_fps: 30
[06/16/24 20:53:36] crowsnest:		custom_flags: --format=UYVY
[06/16/24 20:53:36] crowsnest: INFO: Detect available Devices
[06/16/24 20:53:36] crowsnest: ERROR: No usable Devices Found. Stopping crowsnest.

```

**Comment by mojamuto** [comment]
> Your config says dev/video9. Try video0

I have checked from video0 to video9 and none of them work.

**Comment by zhangyumingsh** [comment]
> Hi, having the same problem. Tested the camera with a Pi and it's working. 3,3V is present when connected to CB2 with M8P V2.
> 
> ```
> [06/16/24 20:53:36] crowsnest: crowsnest - A webcam Service for multiple Cams and Stream Services.
> [06/16/24 20:53:36] crowsnest: Version: v4.1.9-1-gd75a3ae
> [06/16/24 20:53:36] crowsnest: Prepare Startup ...
> [06/16/24 20:53:36] crowsnest: INFO: Host information:
> [06/16/24 20:53:36] crowsnest: Host Info: Distribution: BTT-CB2_1.0.4_Armbian 23.05.0-trunk Bullseye
> [06/16/24 20:53:36] crowsnest: Host Info: Kernel: Linux 4.19.232-bigtree-cb2 aarch64
> [06/16/24 20:53:36] crowsnest: Host Info: Available CPU Cores: 4
> [06/16/24 20:53:36] crowsnest: Host Info: Available Memory: 2029676 kB
> [06/16/24 20:53:36] crowsnest: Host Info: Diskspace (avail. / total): 24G / 29G
> [06/16/24 20:53:36] crowsnest: INFO: Checking Dependencies
> [06/16/24 20:53:36] crowsnest: Dependency: 'crudini' found in /usr/bin/crudini.
> [06/16/24 20:53:36] crowsnest: Dependency: 'find' found in /usr/bin/find.
> [06/16/24 20:53:36] crowsnest: Dependency: 'xargs' found in /usr/bin/xargs.
> [06/16/24 20:53:36] crowsnest: Dependency: 'ustreamer' found in bin/ustreamer/src/ustreamer.bin.
> [06/16/24 20:53:36] crowsnest: Version Control: ustreamer is up to date. (v6.10)
> [06/16/24 20:53:36] crowsnest: INFO: Print Configfile: '/home/philipp/printer_data/config/crowsnest.conf'
> [06/16/24 20:53:36] crowsnest:		[crowsnest]
> [06/16/24 20:53:36] crowsnest:		log_path: /home/philipp/printer_data/logs/crowsnest.log
> [06/16/24 20:53:36] crowsnest:		log_level: verbose
> [06/16/24 20:53:36] crowsnest:		delete_log: false
> [06/16/24 20:53:36] crowsnest:		no_proxy: false
> [06/16/24 20:53:36] crowsnest:		
> [06/16/24 20:53:36] crowsnest:		[cam 1]
> [06/16/24 20:53:36] crowsnest:		mode: ustreamer
> [06/16/24 20:53:36] crowsnest:		
> [06/16/24 20:53:36] crowsnest:		enable_rtsp: false
> [06/16/24 20:53:36] crowsnest:		rtsp_port: 8554
> [06/16/24 20:53:36] crowsnest:		port: 8080
> [06/16/24 20:53:36] crowsnest:		device: /dev/video0
> [06/16/24 20:53:36] crowsnest:		resolution: 1920x1080
> [06/16/24 20:53:36] crowsnest:		max_fps: 30
> [06/16/24 20:53:36] crowsnest:		custom_flags: --format=UYVY
> [06/16/24 20:53:36] crowsnest: INFO: Detect available Devices
> [06/16/24 20:53:36] crowsnest: ERROR: No usable Devices Found. Stopping crowsnest.
> ```

Check if the hardware IO is reversed.Then use i2ctools to see if the device can be scanned,using command :sudo i2cdetect -y 2 
，Finally, read the image with the following command:v4l2-ctl -d /dev/video0 --set-fmt-video=width=640,height=480,pixelformat=NV12 --stream-mmap=3 --stream-skip=3 --stream-to=/usr/nv12.bin --stream-count=1 --stream-poll.If these steps are all correct, according to the document settings, there will definitely be a video stream produced
![1](https://github.com/bigtreetech/CB2/assets/26036538/5d38e715-8353-4426-a194-376c35d1cdf9)
![2](https://github.com/bigtreetech/CB2/assets/26036538/da2048cc-62d3-4f29-a16b-c9d0c70a5f7f)
![3](https://github.com/bigtreetech/CB2/assets/26036538/712ffc1f-800e-448d-b727-c7c6b25b37fe)

**Comment by zhangyumingsh** [comment]
> Hi, having the same problem. Tested the camera with a Pi and it's working. 3,3V is present when connected to CB2 with M8P V2.
> 
> ```
> [06/16/24 20:53:36] crowsnest: crowsnest - A webcam Service for multiple Cams and Stream Services.
> [06/16/24 20:53:36] crowsnest: Version: v4.1.9-1-gd75a3ae
> [06/16/24 20:53:36] crowsnest: Prepare Startup ...
> [06/16/24 20:53:36] crowsnest: INFO: Host information:
> [06/16/24 20:53:36] crowsnest: Host Info: Distribution: BTT-CB2_1.0.4_Armbian 23.05.0-trunk Bullseye
> [06/16/24 20:53:36] crowsnest: Host Info: Kernel: Linux 4.19.232-bigtree-cb2 aarch64
> [06/16/24 20:53:36] crowsnest: Host Info: Available CPU Cores: 4
> [06/16/24 20:53:36] crowsnest: Host Info: Available Memory: 2029676 kB
> [06/16/24 20:53:36] crowsnest: Host Info: Diskspace (avail. / total): 24G / 29G
> [06/16/24 20:53:36] crowsnest: INFO: Checking Dependencies
> [06/16/24 20:53:36] crowsnest: Dependency: 'crudini' found in /usr/bin/crudini.
> [06/16/24 20:53:36] crowsnest: Dependency: 'find' found in /usr/bin/find.
> [06/16/24 20:53:36] crowsnest: Dependency: 'xargs' found in /usr/bin/xargs.
> [06/16/24 20:53:36] crowsnest: Dependency: 'ustreamer' found in bin/ustreamer/src/ustreamer.bin.
> [06/16/24 20:53:36] crowsnest: Version Control: ustreamer is up to date. (v6.10)
> [06/16/24 20:53:36] crowsnest: INFO: Print Configfile: '/home/philipp/printer_data/config/crowsnest.conf'
> [06/16/24 20:53:36] crowsnest:		[crowsnest]
> [06/16/24 20:53:36] crowsnest:		log_path: /home/philipp/printer_data/logs/crowsnest.log
> [06/16/24 20:53:36] crowsnest:		log_level: verbose
> [06/16/24 20:53:36] crowsnest:		delete_log: false
> [06/16/24 20:53:36] crowsnest:		no_proxy: false
> [06/16/24 20:53:36] crowsnest:		
> [06/16/24 20:53:36] crowsnest:		[cam 1]
> [06/16/24 20:53:36] crowsnest:		mode: ustreamer
> [06/16/24 20:53:36] crowsnest:		
> [06/16/24 20:53:36] crowsnest:		enable_rtsp: false
> [06/16/24 20:53:36] crowsnest:		rtsp_port: 8554
> [06/16/24 20:53:36] crowsnest:		port: 8080
> [06/16/24 20:53:36] crowsnest:		device: /dev/video0
> [06/16/24 20:53:36] crowsnest:		resolution: 1920x1080
> [06/16/24 20:53:36] crowsnest:		max_fps: 30
> [06/16/24 20:53:36] crowsnest:		custom_flags: --format=UYVY
> [06/16/24 20:53:36] crowsnest: INFO: Detect available Devices
> [06/16/24 20:53:36] crowsnest: ERROR: No usable Devices Found. Stopping crowsnest.
> ```

The rest will be updated in v1.0.5

**Comment by zhangyumingsh** [comment]
> Good afternoon, I am trying to connect a raspicam v1.3 ov5647, I have followed the instructions in the PDF but I get this error: ![fallo crownest](https://private-user-images.githubusercontent.com/36079583/340125175-c704ec9a-f08b-45e2-9a99-cd996fe05f9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1OTUxMjIsIm5iZiI6MTcxODU5NDgyMiwicGF0aCI6Ii8zNjA3OTU4My8zNDAxMjUxNzUtYzcwNGVjOWEtZjA4Yi00NWUyLTlhOTktY2Q5OTZmZTA1ZjllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDAzMjcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzMWFjYWM5NzdlNDc5NjhlY2UyYzdjMDUwYjZhZjY1NjUwMTUwNjdlMTM3OWUxODIwOTQxZWQ4ZjU2NDAzMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aPH7vzD8oL4mRY7ygo-QUAt0CTDNMQB4JqqjEwKsjnc) Searching on the internet, everything refers to libcamera-hello, but it is not in the Armbian image.

This issue will be updated in v1.0.5

**Comment by igl-x2** [comment]
Will it be possible to Update without losing data / reflash emmc?

**Comment by zhangyumingsh** [comment]
> > Your config says dev/video9. Try video0
> 
> I have checked from video0 to video9 and none of them work.

![set](https://github.com/bigtreetech/CB2/assets/26036538/21109d2b-1854-4ea9-a967-c718fc3be2da)
![showstream](https://github.com/bigtreetech/CB2/assets/26036538/ecf14360-4f0a-4b9d-9b93-e30e2d5b60a5)
You can try the settings shown in the picture.( custom_flags: --format=UYVY )

**Comment by looxonline** [comment]
> > > Your config says dev/video9. Try video0
> > 
> > 
> > I have checked from video0 to video9 and none of them work.
> 
> ![set](https://private-user-images.githubusercontent.com/26036538/343090443-21109d2b-1854-4ea9-a967-c718fc3be2da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTM2MzcsIm5iZiI6MTcxOTM5MzMzNywicGF0aCI6Ii8yNjAzNjUzOC8zNDMwOTA0NDMtMjExMDlkMmItMTg1NC00ZWE5LWE5NjctYzcxOGZjM2JlMmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA5MTUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzNmVjNDM2N2M2Y2M0ZTA2ZDEyZGU4NWY3NmZjMjQ5NDI1OTU0NzU2ZDZjODU3NjhhMzgyYjc2YWU4ZTFiYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Le90PokqirYhCh4vhBGfR38XjczqNvwRVwtvc3xoPus) ![showstream](https://private-user-images.githubusercontent.com/26036538/343090457-ecf14360-4f0a-4b9d-9b93-e30e2d5b60a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTM2MzcsIm5iZiI6MTcxOTM5MzMzNywicGF0aCI6Ii8yNjAzNjUzOC8zNDMwOTA0NTctZWNmMTQzNjAtNGYwYS00YjlkLTliOTMtZTMwZTJkNWI2MGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA5MTUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1NTI4YTBlMjk0ZTE1MDk5MGRiMTI3ODY2MjI3NzNiMDVkMDhmNTQzMmI0NGM1ODhmOTY0YTgwZjRkMDY1ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9tWIO6Db1u0h7kYS2rJ9O_OdpI9GvTZ9i9yiE6RIACM) You can try the settings shown in the picture.( custom_flags: --format=UYVY )

I experience the same problem on my M8P V2.0

**Comment by zhangyumingsh** [comment]
> > Your config says dev/video9. Try video0
> 
> I have checked from video0 to video9 and none of them work.

If there is still no stream according to the previous settings. Scan the OV5647 camera to see if there are any devices for the OV5647. As shown in the figure. If there is no device, there is a communication issue between the motherboard and the m8p.
![Uploading scandev.png…]()

**Comment by zhangyumingsh** [comment]
> > Your config says dev/video9. Try video0
> 
> I have checked from video0 to video9 and none of them work.

If there is still no stream according to the previous settings. Scan the OV5647 camera to see if there are any devices for the OV5647. As shown in the figure. If there is no device, there is a communication issue between the motherboard and the m8p.
![scandev](https://github.com/bigtreetech/CB2/assets/26036538/cccfe834-77ee-4899-b44d-552b6458f6f3)

**Comment by zhangyumingsh** [comment]
> Hi, having the same problem. Tested the camera with a Pi and it's working. 3,3V is present when connected to CB2 with M8P V2.
> 
> ```
> [06/16/24 20:53:36] crowsnest: crowsnest - A webcam Service for multiple Cams and Stream Services.
> [06/16/24 20:53:36] crowsnest: Version: v4.1.9-1-gd75a3ae
> [06/16/24 20:53:36] crowsnest: Prepare Startup ...
> [06/16/24 20:53:36] crowsnest: INFO: Host information:
> [06/16/24 20:53:36] crowsnest: Host Info: Distribution: BTT-CB2_1.0.4_Armbian 23.05.0-trunk Bullseye
> [06/16/24 20:53:36] crowsnest: Host Info: Kernel: Linux 4.19.232-bigtree-cb2 aarch64
> [06/16/24 20:53:36] crowsnest: Host Info: Available CPU Cores: 4
> [06/16/24 20:53:36] crowsnest: Host Info: Available Memory: 2029676 kB
> [06/16/24 20:53:36] crowsnest: Host Info: Diskspace (avail. / total): 24G / 29G
> [06/16/24 20:53:36] crowsnest: INFO: Checking Dependencies
> [06/16/24 20:53:36] crowsnest: Dependency: 'crudini' found in /usr/bin/crudini.
> [06/16/24 20:53:36] crowsnest: Dependency: 'find' found in /usr/bin/find.
> [06/16/24 20:53:36] crowsnest: Dependency: 'xargs' found in /usr/bin/xargs.
> [06/16/24 20:53:36] crowsnest: Dependency: 'ustreamer' found in bin/ustreamer/src/ustreamer.bin.
> [06/16/24 20:53:36] crowsnest: Version Control: ustreamer is up to date. (v6.10)
> [06/16/24 20:53:36] crowsnest: INFO: Print Configfile: '/home/philipp/printer_data/config/crowsnest.conf'
> [06/16/24 20:53:36] crowsnest:		[crowsnest]
> [06/16/24 20:53:36] crowsnest:		log_path: /home/philipp/printer_data/logs/crowsnest.log
> [06/16/24 20:53:36] crowsnest:		log_level: verbose
> [06/16/24 20:53:36] crowsnest:		delete_log: false
> [06/16/24 20:53:36] crowsnest:		no_proxy: false
> [06/16/24 20:53:36] crowsnest:		
> [06/16/24 20:53:36] crowsnest:		[cam 1]
> [06/16/24 20:53:36] crowsnest:		mode: ustreamer
> [06/16/24 20:53:36] crowsnest:		
> [06/16/24 20:53:36] crowsnest:		enable_rtsp: false
> [06/16/24 20:53:36] crowsnest:		rtsp_port: 8554
> [06/16/24 20:53:36] crowsnest:		port: 8080
> [06/16/24 20:53:36] crowsnest:		device: /dev/video0
> [06/16/24 20:53:36] crowsnest:		resolution: 1920x1080
> [06/16/24 20:53:36] crowsnest:		max_fps: 30
> [06/16/24 20:53:36] crowsnest:		custom_flags: --format=UYVY
> [06/16/24 20:53:36] crowsnest: INFO: Detect available Devices
> [06/16/24 20:53:36] crowsnest: ERROR: No usable Devices Found. Stopping crowsnest.
> ```

![config](https://github.com/bigtreetech/CB2/assets/26036538/e6251d65-a317-4331-9caf-c6e36d6418e5)

Try using this configuration

**Comment by zhangyumingsh** [comment]
> Good afternoon, I am trying to connect a raspicam v1.3 ov5647, I have followed the instructions in the PDF but I get this error: ![fallo crownest](https://private-user-images.githubusercontent.com/36079583/340125175-c704ec9a-f08b-45e2-9a99-cd996fe05f9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0ODAyNDAsIm5iZiI6MTcxOTQ3OTk0MCwicGF0aCI6Ii8zNjA3OTU4My8zNDAxMjUxNzUtYzcwNGVjOWEtZjA4Yi00NWUyLTlhOTktY2Q5OTZmZTA1ZjllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA5MTkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ZjQ0YmQ1Mzg4YjRkMjg5YWU1MGFiZWYzMGQ5MDJkNWY2N2VhZmZkMWNmYjVmNWIwMTAxNDRjZmFhYWRhOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Nb2wFYgBAVT5cwcEEP_j-7QRTdiYDPyqy5zmKV3yQoA) Searching on the internet, everything refers to libcamera-hello, but it is not in the Armbian image.

Using v1.0.5 version of image

**Comment by mojamuto** [comment]
1.0.5 fix the problem
