### ISSUE TITLE
BTT-Pi2 Klipper runtime warning 

### ISSUE THREAD

**Issue by EightFinger** [bigtreetech/CB2#2]
I have the BTT Pi2 installed since today, and I get this warning occasionally:
![grafik](https://github.com/bigtreetech/CB2/assets/141996846/1ffe6f9d-65b2-4b99-b9ac-a8e80f871cb3)

![grafik](https://github.com/bigtreetech/CB2/assets/141996846/20d7f393-dd50-4e38-b485-ea57494cab80)

Is this right?

**Comment by Travis90x** [comment]
https://docs.mainsail.xyz/faq/klipper_warnings/runtime-warning

![immagine](https://github.com/bigtreetech/CB2/assets/23300077/bf179b8d-c68f-4a16-88be-311ca764ee20)

**Comment by BTTJUSTIN** [comment]
Thanks for reaching out. Our support team does not operate using the GitHub platform but we would be happy to help you via email based ticketing system. Please visit https://biqu.equipment/pages/technical-support and submit a ticket and we will be in touch with you soon.
