### ISSUE TITLE
MCU 'CB2' configured for 50Mhz but running at 46Mhz!

### ISSUE THREAD

**Issue by Marucci87** [bigtreetech/CB2#20]
I have seen this error 3 times in 1 hours after install. What is the cause and how do I fix it?

**Comment by Marucci87** [comment]
T
his error will not stop showing, anyone else with the same issue?

**Comment by BTTJUSTIN** [comment]
Thanks for reaching out. Our support team does not operate using the GitHub platform but we would be happy to help you via email based ticketing system. Please visit https://biqu.equipment/pages/technical-support and submit a ticket and we will be in touch with you soon.
