### ISSUE TITLE
Debian 12

### ISSUE THREAD

**Issue by bistory** [bigtreetech/CB2#24]
Hi,

This image is still based on Debian 11 while Debian 12 is stable for 1 year.
I have not yet tried to compile a more recent image using Radxa tools ( https://github.com/radxa-repo/rbuild )
Before that, I would like to know if there are plans updating the image to use Debian 12 ?

Thanks !

**Comment by zhangyumingsh** [comment]
> Hi,
> 
> This image is still based on Debian 11 while Debian 12 is stable for 1 year. I have not yet tried to compile a more recent image using Radxa tools ( https://github.com/radxa-repo/rbuild ) Before that, I would like to know if there are plans updating the image to use Debian 12 ?
> 
> Thanks !

The performance of Deban12 is not as good as Deban11, and the performance of Deban12 system needs to be optimized. There are currently no plans to provide images for debian12, unless the debian12 file system performance is optimized and the debian12 image will be released.
