### ISSUE TITLE
How to use DS18B20 on CB2

### ISSUE THREAD

**Issue by oMTEo** [bigtreetech/CB2#25]
As the title says...

I used many DS18B20s on my CB1 followed this guide -> https://gist.github.com/mdvorak/2fccca3fa9f76f5a2e11e567797c76d6

Now Im switched to CB2 and little lost because I get some errors while compiling.

**Comment by BTTJUSTIN** [comment]
Thanks for reaching out. Our support team does not operate using the GitHub platform but we would be happy to help you via email based ticketing system. Please visit https://biqu.equipment/pages/technical-support and submit a ticket and we will be in touch with you soon

**Comment by oMTEo** [comment]
I want the help here so other people can profit from solutions if available...

**Comment by HolyFrank** [comment]
I  want learning too. I have same problem!

**Comment by 35C0lDFuSi0n** [comment]
Did somebody found a solution ?

**Comment by oMTEo** [comment]
No, and thats why I switched to a CM4...

**Comment by bigtreetech** [comment]
We should have some feedback on it in the next day or two.

**Comment by 35C0lDFuSi0n** [comment]
> We should have some feedback on it in the next day or two.

Great, I will patiently wait. 
Thank for your supports.

**Comment by HolyFrank** [comment]
> We should have some feedback on it in the next day or two.

Update?

**Comment by 35C0lDFuSi0n** [comment]
Update?

**Comment by bigtreetech** [comment]
1. Modify the configuration in the "rk3566-w1_gpio.dts" file, ① gpiochip， ②gpioline, 
For example:
GPO1_A0 (gpiochip1/gpio0) is set to gpio1 and 0x00 (hexadecimal),
GPIO4_B2(gpiochip4/gpio10) is set to gpio4 and 0x0a (hexadecimal)
GPIO0_D1(gpiochip0/gpio25) is set to gpio0 and 0x19 (hexadecimal)

<img width="646" height="416" alt="Image" src="https://github.com/user-attachments/assets/f6ce9bed-3530-462c-97ec-12de252d5c1f" />

2. Upload the"rk3566-w1_gpio.dts" file to the CB2 system, enter the command in the command line to compile dts into dtbo
sudo dtc -I dts -O dtb -o rk3566-w1_gpio.dtbo rk3566-w1_gpio.dts
3. Move the compiled rk3566-w1_gpio.dtbo to the path "/boot/dtb/rockchip/overlay/"
sudo mv rk3566-w1_gpio.dtbo /boot/dtb/rockchip/overlay/
4.  Edit "/boot/armbianEnv.txt", add "w1_gpio" configuration in the "overlays" configuration, save and exit, then restart the system.
sudo nano/boot/armbianEnv. txt

<img width="881" height="610" alt="Image" src="https://github.com/user-attachments/assets/4e2ba8eb-124d-4833-ad93-9739551ee547" />

 5. After the system is started, using the "sudo gpioinfo" command can check that the corresponding gpio has been configured with "onewire" functionality

<img width="678" height="570" alt="Image" src="https://github.com/user-attachments/assets/7438ff1a-0343-4177-a081-263617b2a0f3" />


Rename this file from .zip to .dts
[rk3566-w1_gpio.zip](https://github.com/user-attachments/files/21097904/rk3566-w1_gpio.zip)
