### ISSUE TITLE
klipperScreen not boot on TFT35 Img 1.0.5

### ISSUE THREAD

**Issue by iamLellep** [bigtreetech/CB2#28]
Although klipperscreen is correctly installed by default in the CB2 image, the service does not start even when forced from the command line.
Even when updating the version the problem remains.
The screen remains on waiting for login, so it is connected and working properly.
The problem could come from some missing libraries

**Comment by Pneumanifest** [comment]
Ssh in and send this command,
`sudo bash -c "echo needs_root_rights=yes>>/etc/X11/Xwrapper.config"`

**Comment by iamLellep** [comment]
after the commands and the restart it still remains stuck on this screen with the error that the driver is missing and it doesn't show the klipperscreen screen

![Uploading 20240714_114800.jpg…]()

**Comment by klipper-vp** [comment]
Estava com mesmo problema corrigi dessa forma
![BTT1](https://github.com/user-attachments/assets/8faa44f3-d87e-4e33-9dff-95ca0e567225)
![btt2](https://github.com/user-attachments/assets/6a62cc69-47fd-45b1-b4d0-08361565e7e5)
![btt3](https://github.com/user-attachments/assets/6bd1410c-932b-40bb-a11d-13874b9c03c6)

**Comment by klipper-vp** [comment]
me da um FeedBack se foi.

**Comment by iamLellep** [comment]
> me da um FeedBack se foi.

I confirm that it works.  I had not enabled display control in the system.cfg file while I had correctly enabled the tft35 overlay from boardenv.cfg

thank you very much!!

**Comment by klipper-vp** [comment]
Anyway, I'm glad it worked out!!
