### ISSUE TITLE
Camera usb takes a long time to take a picture

### ISSUE THREAD

**Issue by jfml2020** [bigtreetech/CB2#30]
[Uploading crowsnest.log…]()
I installed everything from SD and when everything was configured and working, I transferred everything to EMMC and it took minutes to show the images from the USB camera. With the micro SD card, everything started fine.
I have to go into crowsnest.conf (without modifying anything) and save & restart and it shows the image again as if changing to EMMC the service is frozen.

**I uninstalled Obico and now the camera loads fine

**Comment by BTTJUSTIN** [comment]
Thanks for reaching out. Our support team does not operate using the GitHub platform but we would be happy to help you via email based ticketing system. Please visit https://biqu.equipment/pages/technical-support 
and submit a ticket and we will be in touch with you soon.
