### ISSUE TITLE
LAN LED stay on even without Cat wire installed

### ISSUE THREAD

**Issue by JD13xs** [bigtreetech/CB2#32]
I just started using this CB2 attached to an older pi adapter board. 
The LAN LEDs stay on even without any connected wire to the LAN port.

**Comment by zhangyumingsh** [comment]
> I just started using this CB2 attached to an older pi adapter board. The LAN LEDs stay on even without any connected wire to the LAN port.

Lan's light is always on, it stays on as long as there is power supply. Communication will flash
