### ISSUE TITLE
CB2 build error

### ISSUE THREAD

**Issue by githubniko** [bigtreetech/CB2#39]
Hello.
I'm trying to put together an image for **BIGTREETECH PI2 v1.0.1**

**Build commands:**
git clone -b CB2 --single-branch https://github.com/bigtreetech/build.git
cd build/
./compile.sh build BOARD=bigtreetech-cb2 BRANCH=current BUILD_DESKTOP=no BUILD_MINIMAL=no EXPERT=yes KERNEL_CONFIGURE=no RELEASE=bullseye

The build is for kernel 6.x
**An error occurred during the build:**

> --> (2645) COMMAND: mount --bind /home/user/build/cache/aptcache/lists/bullseye-arm64 /home/user/build/.tmp/rootfs-040efdce-0828-43fd-9eba-b70c82380d13/var/lib/apt/lists
> --> (2645) COMMAND: DEBIAN_FRONTEND=noninteractive ARMBIAN_IMAGE_BUILD_BOOTFS_TYPE=fat apt-get -y -qq -o Dpkg::Use-Pty=0 -o APT::Get::List-Cleanup=0 -o APT::Clean-Installed=0 --no-install-recommends install /root/base-files_24.8.0-trunk-11.1+deb11u11-bullseye_arm64__1-bullseye-1armbian1-B2231-U11.1--deb11u11-R55fa.deb
>    E: Packages were downgraded and -y was used without --allow-downgrades.
>    -->--> command failed with error code 100 after 5 seconds
> --> (2650) WARNING: stacktrace for failed command [ exit code 100:chroot /home/user/build/.tmp/rootfs-040efdce-0828-43fd-9eba-b70c82380d13 /usr/bin/env bash -e -o pipefail -c DEBIAN_FRONTEND=noninteractive ARMBIAN_IMAGE_BUILD_BOOTFS_TYPE=fat apt-get -y -qq -o Dpkg::Use-Pty=0 -o APT::Get::List-Cleanup=0 -o APT::Clean-Installed=0 --no-install-recommends install /root/base-files_24.8.0-trunk-11.1+deb11u11-bullseye_arm64__1-bullseye-1armbian1-B2231-U11.1--deb11u11-R55fa.deb
>                      chroot_sdcard() --> lib/functions/logging/runners.sh:122
>              chroot_sdcard_apt_get() --> lib/functions/logging/runners.sh:107
>                 install_deb_chroot() --> lib/functions/rootfs/apt-install.sh:106
>        install_artifact_deb_chroot() --> lib/functions/rootfs/apt-install.sh:121
>       install_distribution_specific() --> lib/functions/rootfs/distro-specific.sh:40
>                    do_with_logging() --> lib/functions/logging/section-logging.sh:81
>             build_rootfs_and_image() --> lib/functions/main/rootfs-image.sh:27
>       full_build_packages_rootfs_and_image() --> lib/functions/main/default-build.sh:36
>              do_with_default_build() --> lib/functions/main/default-build.sh:42
>             cli_standard_build_run() --> lib/functions/cli/cli-build.sh:25
>            armbian_cli_run_command() --> lib/functions/cli/utils-cli.sh:136
>                     cli_entrypoint() --> lib/functions/cli/entrypoint.sh:176
>                               main() --> compile.sh:50 ]
> --> (2650) ERROR: Error context msg [ Installation of /root/base-files_24.8.0-trunk-11.1+deb11u11-bullseye_arm64__1-bullseye-1armbian1-B2231-U11.1--deb11u11-R55fa.deb failed bigtreetech-cb2 bullseye no cb2 ]
> --> (2650) COMMAND: umount /home/user/build/.tmp/rootfs-040efdce-0828-43fd-9eba-b70c82380d13/var/cache/apt
> --> (2650) COMMAND: umount /home/user/build/.tmp/rootfs-040efdce-0828-43fd-9eba-b70c82380d13/var/lib/apt/lists
> --> (2650) ERROR: Error 1 occurred in main shell [ at /home/user/build/lib/functions/rootfs/apt-install.sh:106
>                 install_deb_chroot() --> lib/functions/rootfs/apt-install.sh:106
>        install_artifact_deb_chroot() --> lib/functions/rootfs/apt-install.sh:121
>       install_distribution_specific() --> lib/functions/rootfs/distro-specific.sh:40
>                    do_with_logging() --> lib/functions/logging/section-logging.sh:81
>             build_rootfs_and_image() --> lib/functions/main/rootfs-image.sh:27
>       full_build_packages_rootfs_and_image() --> lib/functions/main/default-build.sh:36
>              do_with_default_build() --> lib/functions/main/default-build.sh:42
>             cli_standard_build_run() --> lib/functions/cli/cli-build.sh:25
>            armbian_cli_run_command() --> lib/functions/cli/utils-cli.sh:136
>                     cli_entrypoint() --> lib/functions/cli/entrypoint.sh:176
>                               main() --> compile.sh:50
>     ]
> --> (2650) ERROR: Cleaning up [ please wait for cleanups to finish ]
> --> (2650) INFO: Unmounting recursively [ SDCARD - be patient ]
> --> (2651) INFO: Unmounting recursively [ MOUNT - be patient ]

Should I use --allow-downgrades in this case?
What should I do?

**Comment by bigtreetech** [comment]
We will be releasing our own kernel V6.1 image soon. Better to wait on that.
