### ISSUE TITLE
Flashing Klipper 

### ISSUE THREAD

**Issue by acozad1** [bigtreetech/CB2#44]
I cant get klipper or katapult to flash the stm chip for some reason. I keep getting errors when attempting to flash the mcu. I was able to flash the katapult firmware but not the klipper firmware to the mcu. Any help or suggestions would be greatly appreciated.

Failed to flash to /dev/serial/by-id//dev/serial/by-id/usb-Klipper_stm32g0b1xx_momentOS-if00: Unable to find tty device

Nevermind. You have to put it into DFU mode and than FLASH_DEVICE=[your device id using lsusb]

**Comment by Pneumanifest** [comment]
This is not an issue pertaining to the CB2 or the Host computer in general.

**Comment by BTTJUSTIN** [comment]
Thanks for reaching out. Our support team does not operate using the GitHub platform but we would be happy to help you via email based ticketing system. Please visit https://biqu.equipment/pages/technical-support 
and submit a ticket and we will be in touch with you soon.
