### ISSUE TITLE
CB2 image dont boot

### ISSUE THREAD

**Issue by OstroMa** [bigtreetech/CB2#8]
Hi the actual image 1.0.3 don't boot on biqu pi2. 
i flashed the sdcard and their is no boot partition. please correct this.

**Comment by TheFeralEngineer** [comment]
did you use raspberry pi imager, balena etcher or rkdevtool?

**Comment by OstroMa** [comment]
BelenaEtcher

**Comment by TheFeralEngineer** [comment]
I used raspberry pi imager and it works well. Maybe try that

Phil T.
The Feral Engineer

www.theferalengineer.com

Catnip contributions 🐱🐱
https://paypal.me/timpsonmusicllc

**Comment by OstroMa** [comment]
was the powersupply
